// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testFilms(t *testing.T) {
	t.Parallel()

	query := Films()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testFilmsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFilmsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Films().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFilmsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FilmSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFilmsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := FilmExists(ctx, tx, o.FilmID)
	if err != nil {
		t.Errorf("Unable to check if Film exists: %s", err)
	}
	if !e {
		t.Errorf("Expected FilmExists to return true, but got false.")
	}
}

func testFilmsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	filmFound, err := FindFilm(ctx, tx, o.FilmID)
	if err != nil {
		t.Error(err)
	}

	if filmFound == nil {
		t.Error("want a record, got nil")
	}
}

func testFilmsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Films().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testFilmsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Films().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testFilmsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	filmOne := &Film{}
	filmTwo := &Film{}
	if err = randomize.Struct(seed, filmOne, filmDBTypes, false, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}
	if err = randomize.Struct(seed, filmTwo, filmDBTypes, false, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = filmOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = filmTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Films().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testFilmsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	filmOne := &Film{}
	filmTwo := &Film{}
	if err = randomize.Struct(seed, filmOne, filmDBTypes, false, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}
	if err = randomize.Struct(seed, filmTwo, filmDBTypes, false, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = filmOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = filmTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func filmBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func filmAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func filmAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func filmBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func filmAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func filmBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func filmAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func filmBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func filmAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func testFilmsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Film{}
	o := &Film{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, filmDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Film object: %s", err)
	}

	AddFilmHook(boil.BeforeInsertHook, filmBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	filmBeforeInsertHooks = []FilmHook{}

	AddFilmHook(boil.AfterInsertHook, filmAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	filmAfterInsertHooks = []FilmHook{}

	AddFilmHook(boil.AfterSelectHook, filmAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	filmAfterSelectHooks = []FilmHook{}

	AddFilmHook(boil.BeforeUpdateHook, filmBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	filmBeforeUpdateHooks = []FilmHook{}

	AddFilmHook(boil.AfterUpdateHook, filmAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	filmAfterUpdateHooks = []FilmHook{}

	AddFilmHook(boil.BeforeDeleteHook, filmBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	filmBeforeDeleteHooks = []FilmHook{}

	AddFilmHook(boil.AfterDeleteHook, filmAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	filmAfterDeleteHooks = []FilmHook{}

	AddFilmHook(boil.BeforeUpsertHook, filmBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	filmBeforeUpsertHooks = []FilmHook{}

	AddFilmHook(boil.AfterUpsertHook, filmAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	filmAfterUpsertHooks = []FilmHook{}
}

func testFilmsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFilmsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(filmColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFilmToManyFilmActors(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Film
	var b, c FilmActor

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, filmActorDBTypes, false, filmActorColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, filmActorDBTypes, false, filmActorColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.FilmID = a.FilmID
	c.FilmID = a.FilmID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.FilmActors().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.FilmID == b.FilmID {
			bFound = true
		}
		if v.FilmID == c.FilmID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := FilmSlice{&a}
	if err = a.L.LoadFilmActors(ctx, tx, false, (*[]*Film)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.FilmActors); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.FilmActors = nil
	if err = a.L.LoadFilmActors(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.FilmActors); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testFilmToManyFilmCategories(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Film
	var b, c FilmCategory

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, filmCategoryDBTypes, false, filmCategoryColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, filmCategoryDBTypes, false, filmCategoryColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.FilmID = a.FilmID
	c.FilmID = a.FilmID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.FilmCategories().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.FilmID == b.FilmID {
			bFound = true
		}
		if v.FilmID == c.FilmID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := FilmSlice{&a}
	if err = a.L.LoadFilmCategories(ctx, tx, false, (*[]*Film)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.FilmCategories); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.FilmCategories = nil
	if err = a.L.LoadFilmCategories(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.FilmCategories); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testFilmToManyInventories(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Film
	var b, c Inventory

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, inventoryDBTypes, false, inventoryColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, inventoryDBTypes, false, inventoryColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.FilmID = a.FilmID
	c.FilmID = a.FilmID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Inventories().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.FilmID == b.FilmID {
			bFound = true
		}
		if v.FilmID == c.FilmID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := FilmSlice{&a}
	if err = a.L.LoadInventories(ctx, tx, false, (*[]*Film)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Inventories); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Inventories = nil
	if err = a.L.LoadInventories(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Inventories); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testFilmToManyAddOpFilmActors(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Film
	var b, c, d, e FilmActor

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, filmDBTypes, false, strmangle.SetComplement(filmPrimaryKeyColumns, filmColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*FilmActor{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, filmActorDBTypes, false, strmangle.SetComplement(filmActorPrimaryKeyColumns, filmActorColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*FilmActor{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddFilmActors(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.FilmID != first.FilmID {
			t.Error("foreign key was wrong value", a.FilmID, first.FilmID)
		}
		if a.FilmID != second.FilmID {
			t.Error("foreign key was wrong value", a.FilmID, second.FilmID)
		}

		if first.R.Film != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Film != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.FilmActors[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.FilmActors[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.FilmActors().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testFilmToManyAddOpFilmCategories(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Film
	var b, c, d, e FilmCategory

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, filmDBTypes, false, strmangle.SetComplement(filmPrimaryKeyColumns, filmColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*FilmCategory{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, filmCategoryDBTypes, false, strmangle.SetComplement(filmCategoryPrimaryKeyColumns, filmCategoryColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*FilmCategory{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddFilmCategories(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.FilmID != first.FilmID {
			t.Error("foreign key was wrong value", a.FilmID, first.FilmID)
		}
		if a.FilmID != second.FilmID {
			t.Error("foreign key was wrong value", a.FilmID, second.FilmID)
		}

		if first.R.Film != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Film != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.FilmCategories[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.FilmCategories[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.FilmCategories().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testFilmToManyAddOpInventories(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Film
	var b, c, d, e Inventory

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, filmDBTypes, false, strmangle.SetComplement(filmPrimaryKeyColumns, filmColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Inventory{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, inventoryDBTypes, false, strmangle.SetComplement(inventoryPrimaryKeyColumns, inventoryColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Inventory{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddInventories(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.FilmID != first.FilmID {
			t.Error("foreign key was wrong value", a.FilmID, first.FilmID)
		}
		if a.FilmID != second.FilmID {
			t.Error("foreign key was wrong value", a.FilmID, second.FilmID)
		}

		if first.R.Film != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Film != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Inventories[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Inventories[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Inventories().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testFilmToOneLanguageUsingLanguage(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Film
	var foreign Language

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, filmDBTypes, false, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, languageDBTypes, false, languageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Language struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.LanguageID = foreign.LanguageID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Language().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.LanguageID != foreign.LanguageID {
		t.Errorf("want: %v, got %v", foreign.LanguageID, check.LanguageID)
	}

	slice := FilmSlice{&local}
	if err = local.L.LoadLanguage(ctx, tx, false, (*[]*Film)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Language == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Language = nil
	if err = local.L.LoadLanguage(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Language == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testFilmToOneSetOpLanguageUsingLanguage(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Film
	var b, c Language

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, filmDBTypes, false, strmangle.SetComplement(filmPrimaryKeyColumns, filmColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, languageDBTypes, false, strmangle.SetComplement(languagePrimaryKeyColumns, languageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, languageDBTypes, false, strmangle.SetComplement(languagePrimaryKeyColumns, languageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Language{&b, &c} {
		err = a.SetLanguage(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Language != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Films[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.LanguageID != x.LanguageID {
			t.Error("foreign key was wrong value", a.LanguageID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.LanguageID))
		reflect.Indirect(reflect.ValueOf(&a.LanguageID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.LanguageID != x.LanguageID {
			t.Error("foreign key was wrong value", a.LanguageID, x.LanguageID)
		}
	}
}

func testFilmsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFilmsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FilmSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFilmsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Films().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	filmDBTypes = map[string]string{`FilmID`: `integer`, `Title`: `character varying`, `Description`: `text`, `ReleaseYear`: `integer`, `LanguageID`: `integer`, `RentalDuration`: `smallint`, `RentalRate`: `numeric`, `Length`: `smallint`, `ReplacementCost`: `numeric`, `Rating`: `enum.mpaa_rating('G','PG','PG-13','R','NC-17')`, `LastUpdate`: `timestamp without time zone`, `SpecialFeatures`: `ARRAYtext`, `Fulltext`: `tsvector`}
	_           = bytes.MinRead
)

func testFilmsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(filmPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(filmAllColumns) == len(filmPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, filmDBTypes, true, filmPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testFilmsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(filmAllColumns) == len(filmPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, filmDBTypes, true, filmPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(filmAllColumns, filmPrimaryKeyColumns) {
		fields = filmAllColumns
	} else {
		fields = strmangle.SetComplement(
			filmAllColumns,
			filmPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := FilmSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testFilmsUpsert(t *testing.T) {
	t.Parallel()

	if len(filmAllColumns) == len(filmPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Film{}
	if err = randomize.Struct(seed, &o, filmDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Film: %s", err)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, filmDBTypes, false, filmPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Film: %s", err)
	}

	count, err = Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
