version: '3'

services:
  db:
    restart: always
    image: postgres:12-alpine
    container_name: study-sql-boiler-example-container
    ports:
      - "11411:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localpass
      - PGPASSWORD=localpass
      - POSTGRES_DB=sqlboilerexample
      - DATABASE_HOST=localhost
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
